"""initial_schema_and_website_evidence

Revision ID: b911e41b6a6d
Revises: 
Create Date: 2026-10-04 00:18:25.280293

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b911e41b6a6d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {col["name"] for col in inspector.get_columns("website_checks")}

    columns_to_add = [
        ("meta_description", sa.Column("meta_description", sa.String(length=500), nullable=True)),
        ("redirect_chain", sa.Column("redirect_chain", sa.Text(), nullable=True)),
        ("has_robots_txt", sa.Column("has_robots_txt", sa.Boolean(), nullable=True)),
        ("has_sitemap", sa.Column("has_sitemap", sa.Boolean(), nullable=True)),
        ("is_parked", sa.Column("is_parked", sa.Boolean(), nullable=False, server_default=sa.text("0"))),
        ("name_matched", sa.Column("name_matched", sa.Boolean(), nullable=True)),
        ("phone_matched", sa.Column("phone_matched", sa.Boolean(), nullable=True)),
        ("confidence_score", sa.Column("confidence_score", sa.Float(), nullable=True)),
    ]
    for col_name, col_def in columns_to_add:
        if col_name not in existing_cols:
            op.add_column("website_checks", col_def)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_checks', 'confidence_score')
    op.drop_column('website_checks', 'phone_matched')
    op.drop_column('website_checks', 'name_matched')
    op.drop_column('website_checks', 'is_parked')
    op.drop_column('website_checks', 'has_sitemap')
    op.drop_column('website_checks', 'has_robots_txt')
    op.drop_column('website_checks', 'redirect_chain')
    op.drop_column('website_checks', 'meta_description')
    # ### end Alembic commands ###
